Add external links
elastic/ems-landing-page pull request #236
Opened 2020-09-14 19:09 UTC by nickpeihl

Fixes #235 and #140 

This PR would add links to the EMS Terms of Service and this GitHub repo to https://maps.elastic.co. 

Additionally, the link for reporting data issues is changed to the ems-file-service repo.

cc @mbarretta @richardim

2020-09-14 19:13 UTC, kibanamachine commented
## :green_heart: Build Succeeded
* [continuous-integration/kibana-ci/pull-request](https://kibana-ci.elastic.co/job/elastic+ems-landing-page+pull-request/144/)

2020-09-14 19:15 UTC, thomasneirynck approved these changes
code review lgtm

2020-09-14 19:15 UTC, thomasneirynck commented on public/js/components/app.js
> +                  <p>
nice fix of no longer pointing to kibana repo

2020-09-15 10:00 UTC, jsanz requested changes
What about having the icons in the top navigation bar?

![image](https://user-images.githubusercontent.com/188264/93196463-c2704680-f74a-11ea-91c4-44dab435ad81.png)


I had to update EUI to the last version, but this is the snippet of the header

```xml
<EuiHeader>
  <EuiHeaderSectionItem border="right">
    <EuiHeaderLogo href="#" aria-label="Go to elastic.co" iconType="emsApp" >Elastic Maps Service</EuiHeaderLogo>
  </EuiHeaderSectionItem>
  <EuiHeaderSectionItem border="none">
    <EuiHeaderLinks>
      <EuiHeaderLink href="https://elastic.co">elastic.co</EuiHeaderLink>
      <EuiHeaderLink href="https://www.github.com/elastic/ems-landing-page"> Github </EuiHeaderLink>
      <EuiHeaderLink href="https://www.github.com/elastic/ems-file-service/issues/new"> Report data issues </EuiHeaderLink>
      <EuiHeaderLink href="https://www.elastic.co/elastic-maps-service-terms"> Terms of Service </EuiHeaderLink>
    </EuiHeaderLinks>
  </EuiHeaderSectionItem>
</EuiHeader>
```

2020-09-15 15:33 UTC, nickpeihl commented
> What about having the icons in the top navigation bar?
> 
> ![image](https://user-images.githubusercontent.com/188264/93196463-c2704680-f74a-11ea-91c4-44dab435ad81.png)

Good idea, however, I was thinking of reserving space on the top bar for identifying the EMS version (https://github.com/elastic/ems-landing-page/issues/203) and possibly changing the current EMS version (select box?) if we implement client-side routing (https://github.com/elastic/ems-landing-page/issues/226). Do you think we have enough space there for all of that? Or maybe the EMS version goes somewhere else?

2020-09-15 17:08 UTC, jsanz commented
I like not having to scroll down for those links, we can shorten them a bit like

`Version 7.10 | Code | Issues | Terms`


I don't think there will be space issues, and I like EUI frontpage header.

2020-09-15 17:30 UTC, kibanamachine commented
## :green_heart: Build Succeeded
* [continuous-integration/kibana-ci/pull-request](https://kibana-ci.elastic.co/job/elastic+ems-landing-page+pull-request/145/)

2020-09-15 17:34 UTC, jsanz approved these changes
:+1:

2020-09-17 19:12 UTC, merged