Add support for localized basemap labels, remove initial file layer selection
elastic/ems-landing-page pull request #434
Opened 2022-05-23 15:17 UTC by jsanz

This is a new PR coming from #429 only adding the custom language part:

* Removes the initial selection of a file layer to just display the basemap
* Label layers on the map style are rendered on top of selected file layer
* Adds a new form control to allow changing the language of the basemap labels

2022-05-23 19:51 UTC, nickpeihl requested changes
This is a really great feature both in Kibana and landing page. I just have a few suggestions before approving it.

2022-05-23 19:51 UTC, nickpeihl commented on public/js/components/app.js
> +  async _updateMap(state = this.state, mlMap = this?._map?._maplibreMap) {
I think `_updateMap` shouldn't need any arguments since this method has access to `this.state` and `this.map` from the component.

2022-05-23 19:51 UTC, nickpeihl commented on public/js/components/app.js
>                <EuiPageContent>
I don't think we should see the "No items found" empty state when no vector layers are selected. It should look more like this.
![localhost_8080_](https://user-images.githubusercontent.com/1638483/169893370-ec1aa9dd-e7c6-46b7-9dbe-e99f90498325.png)



I think this entire `EuiPageContent` section should be inside a conditional where it only renders if `this.state.selectedFileLayer` is not null. Maybe move this section to a new private method like: 

```
_renderVectorLayerDetails() {
  if (!this.state.selectedFileLayer) {
    return null;
  }

   return (
     <EuiPageContent>
     ...
   )
}
```

Then this line could be replaced by `{ this.renderVectorLayerDetails() }`.

2022-05-23 19:51 UTC, nickpeihl commented on public/js/components/table_of_contents.js
> +        };
Is there a specific reason to switch these to updater functions? It does not look like we are using the previous state to calculate the new state.

2022-05-23 19:51 UTC, nickpeihl commented on public/js/components/map.js
> +  setOverlayLayer(featureCollection, skipZoom, fillColor) {
Do we need the `fillColor` argument in this method? It appears we are not using it here: https://github.com/elastic/ems-landing-page/pull/434/files#diff-9434551f43e9098c79721e425c74dc346a9606ade3caed934c86c6e0a99d3213R80.

2022-05-24 12:45 UTC, jsanz commented on public/js/components/app.js
> +      }, async () => {
Agreed, I can't recall why I moved those objects into a function but it's definitely not necessary, thanks.

2022-05-24 12:46 UTC, jsanz commented on public/js/components/customize_tms.js
> +    this.state = {
That's correct, thanks. I removed the state from the component and the selected option is derived directly from the prop :pray:

2022-05-24 13:32 UTC, jsanz commented on public/js/components/map.js
> +  setOverlayLayer(featureCollection, skipZoom, fillColor) {
Sorry this is a missed piece to move to the follow up PR #435, moving the code there.

2022-05-24 13:34 UTC, jsanz commented on public/js/components/table_of_contents.js
> +        };
You are right, thanks, I've removed the function from those `setState` :pray:

2022-05-24 13:38 UTC, kibanamachine commented
## :green_heart: Build Succeeded
* [continuous-integration/kibana-ci/pull-request](https://kibana-ci.elastic.co/job/elastic+ems-landing-page+pull-request/400/)

2022-05-24 15:15 UTC, kibanamachine commented
## :green_heart: Build Succeeded
* [continuous-integration/kibana-ci/pull-request](https://kibana-ci.elastic.co/job/elastic+ems-landing-page+pull-request/401/)

2022-05-25 10:03 UTC, kibanamachine commented
## :green_heart: Build Succeeded
* [continuous-integration/kibana-ci/pull-request](https://kibana-ci.elastic.co/job/elastic+ems-landing-page+pull-request/403/)

2022-05-25 11:28 UTC, jsanz commented on public/js/components/app.js
> +        console.error(`Error transforming to ${lang}`);
Added support for throwing a toast on errors. This will be more useful for color blending, where users can edit the hex code, generating invalid values.

Check for `_addToast` calls and definition. I'm assuming it would only be need for errors at this moment.

2022-05-25 11:29 UTC, kibanamachine commented
## :green_heart: Build Succeeded
* [continuous-integration/kibana-ci/pull-request](https://kibana-ci.elastic.co/job/elastic+ems-landing-page+pull-request/406/)

2022-05-25 11:31 UTC, jsanz commented on public/js/components/app.js
>                <EuiPageContent>
I tried this approach, but the problem is that not rendering the table at all when loading the page makes later to select a layer impossible because the `FeatureTable` component does not have the reference to the `setFeatureTable` method. 

Let's discuss this synchronously.

2022-05-26 14:27 UTC, jsanz commented on public/js/components/app.js
>                <EuiPageContent>
Discussed off-line, solved on 988024c

2022-05-26 15:10 UTC, nickpeihl approved these changes
changes lgtm!

2022-05-26 15:18 UTC, merged