Dependencies upgrade
elastic/ems-landing-page pull request #711
Opened 2024-02-21 16:16 UTC by jsanz

fixes #629

General upgrade of all dependencies. Relevant upgrades include:

* EUI 93.2.0
* Maplibre 4.02 involved a minor change in code to replace a deprecated function
* React 18.2.0
* Husky 9 involved a change, moving from a section in `package.json` to a new file in a `.husky` folder

I also decided to remove the favicons management from the webpack tooling to reduce the libraries footprint, given the small gain for this page usage.

`libyear` report says:

```
# Collective
drift: package is 0 libyears behind.
pulse: dependencies are 52.18 libyears behind.
releases: dependencies are 0 releases behind.
major: dependencies are 0 releases behind.
minor: dependencies are 0 releases behind.
patch: dependencies are 0 releases behind.
```

2024-02-21 16:20 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/ems-landing-page/builds/435)
* Commit: 0e9bba3964628a6765ccdcf087a905d4f745a60e

<!--buildkite-pr-comment-ems-landing-page
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/ems-landing-page/builds/435","number":435,"commit":"0e9bba3964628a6765ccdcf087a905d4f745a60e"}],"number":435}
buildkite-pr-comment-->

2024-03-01 16:02 UTC, nickpeihl requested changes

2024-03-01 16:02 UTC, nickpeihl commented on public/js/components/map.js
> +    // https://github.com/idofilin/webgl-by-example/blob/master/detect-webgl/detect-webgl.js
This code is [Mozilla Public License 2](https://github.com/idofilin/webgl-by-example/blob/master/detect-webgl/LICENSE). Per our Open Source Policy, for use of this code we also need to include NOTICE file that links to a URL providing the MPL-covered source code.

2024-03-06 14:53 UTC, jsanz commented on public/js/components/map.js
> +    // https://github.com/idofilin/webgl-by-example/blob/master/detect-webgl/detect-webgl.js
Thanks for pointing this out. I've added a NOTICE file at 7fac0fa.

2024-03-06 14:55 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/ems-landing-page/builds/437)
* Commit: 7fac0fa066f0179ef8d1477daa8b6b157c85ae4d

### History
* :green_heart: [Build #435](https://buildkite.com/elastic/ems-landing-page/builds/435) succeeded 0e9bba3964628a6765ccdcf087a905d4f745a60e

<!--buildkite-pr-comment-ems-landing-page
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/ems-landing-page/builds/437","number":437,"commit":"7fac0fa066f0179ef8d1477daa8b6b157c85ae4d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/ems-landing-page/builds/435","number":435,"commit":"0e9bba3964628a6765ccdcf087a905d4f745a60e"}],"number":437}
buildkite-pr-comment-->

2024-03-08 15:43 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/ems-landing-page/builds/448)
* Commit: 9ae0f86cce4b69a7957fb4d0630f1f1ccac70375

### History
* :green_heart: [Build #437](https://buildkite.com/elastic/ems-landing-page/builds/437) succeeded 7fac0fa066f0179ef8d1477daa8b6b157c85ae4d
* :green_heart: [Build #435](https://buildkite.com/elastic/ems-landing-page/builds/435) succeeded 0e9bba3964628a6765ccdcf087a905d4f745a60e

<!--buildkite-pr-comment-ems-landing-page
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/ems-landing-page/builds/448","number":448,"commit":"9ae0f86cce4b69a7957fb4d0630f1f1ccac70375"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/ems-landing-page/builds/437","number":437,"commit":"7fac0fa066f0179ef8d1477daa8b6b157c85ae4d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/ems-landing-page/builds/435","number":435,"commit":"0e9bba3964628a6765ccdcf087a905d4f745a60e"}],"number":448}
buildkite-pr-comment-->

2024-03-08 18:17 UTC, merged

2024-03-22 14:00 UTC, jsanz commented
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|v8.14|Cherrypick failed because the selected commit (8f4345e1) is empty. It looks like the commit was already backported in https://github.com/elastic/ems-landing-page/pull/717|
|❌|v8.13|Cherrypick failed because the selected commit (8f4345e1) is empty. It looks like the commit was already backported in https://github.com/elastic/ems-landing-page/pull/718|
|❌|v8.12|Cherrypick failed because the selected commit (8f4345e1) is empty. It looks like the commit was already backported in https://github.com/elastic/ems-landing-page/pull/719|
|✅|v7.17|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/ems-landing-page/727">](https://github.com/elastic/ems-landing-page/pull/727)|

### Manual backport
To create the backport manually run:
```
backport --pr 711
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

<!--- Backport version: 9.4.5 -->